/* reading from the same location to different destination locations
 *
 * Author: Pranith Kumar
 */


#include <stdio.h>
#include <stdlib.h>

#define USE_BARRIER 1
#include "../barrier.h"
#include "../timer.h"
#include "defines.h"

long *src;
long result;
unsigned long size;

#define KB(x) ((x) << 10)
#define MB(x) ((x) << 20)

void warmup()
{
  unsigned long j;
  size = MB(64) / sizeof(long);
  src = (long *)malloc(sizeof(long) * size);
  //initialize array
  for (j = 0; j < size; j++)
    src[j] = 8;
}


int main(int argc, char* argv[])
{
  warmup();
  unsigned long j;
  volatile long dest = 0;
  int num_mem_ops = 400;
  int final = 0, num_req = 0;

  if (argc > 1)
	  num_req = atoi(argv[1]);

  unsigned long repeat, num_iter = 500000000 / num_mem_ops;
  struct timespec before, after;

  for (repeat = 0; repeat < 5; repeat++) {
  start_watch(&before);
  for(j = 0; j < num_iter; j++)
  {
    dest = src[indexarr0];
    dest = src[indexarr1];
    dest = src[indexarr2];
    dest = src[indexarr3];
    dest = src[indexarr4];
    dest = src[indexarr5];
    dest = src[indexarr6];
    dest = src[indexarr7];
    dest = src[indexarr8];
    dest = src[indexarr9];
    dest = src[indexarr10];
    dest = src[indexarr11];
    dest = src[indexarr12];
    dest = src[indexarr13];
    dest = src[indexarr14];
    dest = src[indexarr15];
    dest = src[indexarr16];
    dest = src[indexarr17];
    dest = src[indexarr18];
    dest = src[indexarr19];
    dest = src[indexarr20];
    dest = src[indexarr21];
    dest = src[indexarr22];
    dest = src[indexarr23];
    dest = src[indexarr24];
    dest = src[indexarr25];
    dest = src[indexarr26];
    dest = src[indexarr27];
    dest = src[indexarr28];
    dest = src[indexarr29];
    dest = src[indexarr30];
    dest = src[indexarr31];
    dest = src[indexarr32];
    dest = src[indexarr33];
    dest = src[indexarr34];
    dest = src[indexarr35];
    dest = src[indexarr36];
    dest = src[indexarr37];
    dest = src[indexarr38];
    dest = src[indexarr39];
    dest = src[indexarr40];
    dest = src[indexarr41];
    dest = src[indexarr42];
    dest = src[indexarr43];
    dest = src[indexarr44];
    dest = src[indexarr45];
    dest = src[indexarr46];
    dest = src[indexarr47];
    dest = src[indexarr48];
    dest = src[indexarr49];
    dest = src[indexarr50];
    dest = src[indexarr51];
    dest = src[indexarr52];
    dest = src[indexarr53];
    dest = src[indexarr54];
    dest = src[indexarr55];
    dest = src[indexarr56];
    dest = src[indexarr57];
    dest = src[indexarr58];
    dest = src[indexarr59];
    dest = src[indexarr60];
    dest = src[indexarr61];
    dest = src[indexarr62];
    dest = src[indexarr63];
    dest = src[indexarr64];
    dest = src[indexarr65];
    dest = src[indexarr66];
    dest = src[indexarr67];
    dest = src[indexarr68];
    dest = src[indexarr69];
    dest = src[indexarr70];
    dest = src[indexarr71];
    dest = src[indexarr72];
    dest = src[indexarr73];
    dest = src[indexarr74];
    dest = src[indexarr75];
    dest = src[indexarr76];
    dest = src[indexarr77];
    dest = src[indexarr78];
    dest = src[indexarr79];
    dest = src[indexarr80];
    dest = src[indexarr81];
    dest = src[indexarr82];
    dest = src[indexarr83];
    dest = src[indexarr84];
    dest = src[indexarr85];
    dest = src[indexarr86];
    dest = src[indexarr87];
    dest = src[indexarr88];
    dest = src[indexarr89];
    dest = src[indexarr90];
    dest = src[indexarr91];
    dest = src[indexarr92];
    dest = src[indexarr93];
    dest = src[indexarr94];
    dest = src[indexarr95];
    dest = src[indexarr96];
    dest = src[indexarr97];
    dest = src[indexarr98];
    dest = src[indexarr99];
    dest = src[indexarr100];
    dest = src[indexarr101];
    dest = src[indexarr102];
    dest = src[indexarr103];
    dest = src[indexarr104];
    dest = src[indexarr105];
    dest = src[indexarr106];
    dest = src[indexarr107];
    dest = src[indexarr108];
    dest = src[indexarr109];
    dest = src[indexarr110];
    dest = src[indexarr111];
    dest = src[indexarr112];
    dest = src[indexarr113];
    dest = src[indexarr114];
    dest = src[indexarr115];
    dest = src[indexarr116];
    dest = src[indexarr117];
    dest = src[indexarr118];
    dest = src[indexarr119];
    dest = src[indexarr120];
    dest = src[indexarr121];
    dest = src[indexarr122];
    dest = src[indexarr123];
    dest = src[indexarr124];
    dest = src[indexarr125];
    dest = src[indexarr126];
    dest = src[indexarr127];
    dest = src[indexarr128];
    dest = src[indexarr129];
    dest = src[indexarr130];
    dest = src[indexarr131];
    dest = src[indexarr132];
    dest = src[indexarr133];
    dest = src[indexarr134];
    dest = src[indexarr135];
    dest = src[indexarr136];
    dest = src[indexarr137];
    dest = src[indexarr138];
    dest = src[indexarr139];
    dest = src[indexarr140];
    dest = src[indexarr141];
    dest = src[indexarr142];
    dest = src[indexarr143];
    dest = src[indexarr144];
    dest = src[indexarr145];
    dest = src[indexarr146];
    dest = src[indexarr147];
    dest = src[indexarr148];
    dest = src[indexarr149];
    dest = src[indexarr150];
    dest = src[indexarr151];
    dest = src[indexarr152];
    dest = src[indexarr153];
    dest = src[indexarr154];
    dest = src[indexarr155];
    dest = src[indexarr156];
    dest = src[indexarr157];
    dest = src[indexarr158];
    dest = src[indexarr159];
    dest = src[indexarr160];
    dest = src[indexarr161];
    dest = src[indexarr162];
    dest = src[indexarr163];
    dest = src[indexarr164];
    dest = src[indexarr165];
    dest = src[indexarr166];
    dest = src[indexarr167];
    dest = src[indexarr168];
    dest = src[indexarr169];
    dest = src[indexarr170];
    dest = src[indexarr171];
    dest = src[indexarr172];
    dest = src[indexarr173];
    dest = src[indexarr174];
    dest = src[indexarr175];
    dest = src[indexarr176];
    dest = src[indexarr177];
    dest = src[indexarr178];
    dest = src[indexarr179];
    dest = src[indexarr180];
    dest = src[indexarr181];
    dest = src[indexarr182];
    dest = src[indexarr183];
    dest = src[indexarr184];
    dest = src[indexarr185];
    dest = src[indexarr186];
    dest = src[indexarr187];
    dest = src[indexarr188];
    dest = src[indexarr189];
    dest = src[indexarr190];
    dest = src[indexarr191];
    dest = src[indexarr192];
    dest = src[indexarr193];
    dest = src[indexarr194];
    dest = src[indexarr195];
    dest = src[indexarr196];
    dest = src[indexarr197];
    dest = src[indexarr198];
    dest = src[indexarr199];
    dest = src[indexarr200];
    dest = src[indexarr201];
    dest = src[indexarr202];
    dest = src[indexarr203];
    dest = src[indexarr204];
    dest = src[indexarr205];
    dest = src[indexarr206];
    dest = src[indexarr207];
    dest = src[indexarr208];
    dest = src[indexarr209];
    dest = src[indexarr210];
    dest = src[indexarr211];
    dest = src[indexarr212];
    dest = src[indexarr213];
    dest = src[indexarr214];
    dest = src[indexarr215];
    dest = src[indexarr216];
    dest = src[indexarr217];
    dest = src[indexarr218];
    dest = src[indexarr219];
    dest = src[indexarr220];
    dest = src[indexarr221];
    dest = src[indexarr222];
    dest = src[indexarr223];
    dest = src[indexarr224];
    dest = src[indexarr225];
    dest = src[indexarr226];
    dest = src[indexarr227];
    dest = src[indexarr228];
    dest = src[indexarr229];
    dest = src[indexarr230];
    dest = src[indexarr231];
    dest = src[indexarr232];
    dest = src[indexarr233];
    dest = src[indexarr234];
    dest = src[indexarr235];
    dest = src[indexarr236];
    dest = src[indexarr237];
    dest = src[indexarr238];
    dest = src[indexarr239];
    dest = src[indexarr240];
    dest = src[indexarr241];
    dest = src[indexarr242];
    dest = src[indexarr243];
    dest = src[indexarr244];
    dest = src[indexarr245];
    dest = src[indexarr246];
    dest = src[indexarr247];
    dest = src[indexarr248];
    dest = src[indexarr249];
    dest = src[indexarr250];
    dest = src[indexarr251];
    dest = src[indexarr252];
    dest = src[indexarr253];
    dest = src[indexarr254];
    dest = src[indexarr255];
    dest = src[indexarr256];
    dest = src[indexarr257];
    dest = src[indexarr258];
    dest = src[indexarr259];
    dest = src[indexarr260];
    dest = src[indexarr261];
    dest = src[indexarr262];
    dest = src[indexarr263];
    dest = src[indexarr264];
    dest = src[indexarr265];
    dest = src[indexarr266];
    dest = src[indexarr267];
    dest = src[indexarr268];
    dest = src[indexarr269];
    dest = src[indexarr270];
    dest = src[indexarr271];
    dest = src[indexarr272];
    dest = src[indexarr273];
    dest = src[indexarr274];
    dest = src[indexarr275];
    dest = src[indexarr276];
    dest = src[indexarr277];
    dest = src[indexarr278];
    dest = src[indexarr279];
    dest = src[indexarr280];
    dest = src[indexarr281];
    dest = src[indexarr282];
    dest = src[indexarr283];
    dest = src[indexarr284];
    dest = src[indexarr285];
    dest = src[indexarr286];
    dest = src[indexarr287];
    dest = src[indexarr288];
    dest = src[indexarr289];
    dest = src[indexarr290];
    dest = src[indexarr291];
    dest = src[indexarr292];
    dest = src[indexarr293];
    dest = src[indexarr294];
    dest = src[indexarr295];
    dest = src[indexarr296];
    dest = src[indexarr297];
    dest = src[indexarr298];
    dest = src[indexarr299];
    dest = src[indexarr300];
    dest = src[indexarr301];
    dest = src[indexarr302];
    dest = src[indexarr303];
    dest = src[indexarr304];
    dest = src[indexarr305];
    dest = src[indexarr306];
    dest = src[indexarr307];
    dest = src[indexarr308];
    dest = src[indexarr309];
    dest = src[indexarr310];
    dest = src[indexarr311];
    dest = src[indexarr312];
    dest = src[indexarr313];
    dest = src[indexarr314];
    dest = src[indexarr315];
    dest = src[indexarr316];
    dest = src[indexarr317];
    dest = src[indexarr318];
    dest = src[indexarr319];
    dest = src[indexarr320];
    dest = src[indexarr321];
    dest = src[indexarr322];
    dest = src[indexarr323];
    dest = src[indexarr324];
    dest = src[indexarr325];
    dest = src[indexarr326];
    dest = src[indexarr327];
    dest = src[indexarr328];
    dest = src[indexarr329];
    dest = src[indexarr330];
    dest = src[indexarr331];
    dest = src[indexarr332];
    dest = src[indexarr333];
    dest = src[indexarr334];
    dest = src[indexarr335];
    dest = src[indexarr336];
    dest = src[indexarr337];
    dest = src[indexarr338];
    dest = src[indexarr339];
    dest = src[indexarr340];
    dest = src[indexarr341];
    dest = src[indexarr342];
    dest = src[indexarr343];
    dest = src[indexarr344];
    dest = src[indexarr345];
    dest = src[indexarr346];
    dest = src[indexarr347];
    dest = src[indexarr348];
    dest = src[indexarr349];
    dest = src[indexarr350];
    dest = src[indexarr351];
    dest = src[indexarr352];
    dest = src[indexarr353];
    dest = src[indexarr354];
    dest = src[indexarr355];
    dest = src[indexarr356];
    dest = src[indexarr357];
    dest = src[indexarr358];
    dest = src[indexarr359];
    dest = src[indexarr360];
    dest = src[indexarr361];
    dest = src[indexarr362];
    dest = src[indexarr363];
    dest = src[indexarr364];
    dest = src[indexarr365];
    dest = src[indexarr366];
    dest = src[indexarr367];
    dest = src[indexarr368];
    dest = src[indexarr369];
    dest = src[indexarr370];
    dest = src[indexarr371];
    dest = src[indexarr372];
    dest = src[indexarr373];
    dest = src[indexarr374];
    dest = src[indexarr375];
    dest = src[indexarr376];
    dest = src[indexarr377];
    dest = src[indexarr378];
    dest = src[indexarr379];
    dest = src[indexarr380];
    dest = src[indexarr381];
    dest = src[indexarr382];
    dest = src[indexarr383];
    dest = src[indexarr384];
    dest = src[indexarr385];
    dest = src[indexarr386];
    dest = src[indexarr387];
    dest = src[indexarr388];
    dest = src[indexarr389];
    dest = src[indexarr390];
    dest = src[indexarr391];
    dest = src[indexarr392];
    dest = src[indexarr393];
    dest = src[indexarr394];
    dest = src[indexarr395];
    dest = src[indexarr396];
    dest = src[indexarr397];
    dest = src[indexarr398];
    dest = src[indexarr399];

    // flush write buffer
    barrier();

    final += dest;
  }
  stop_watch(&after);
  }

  printf("%ld, %d\n", get_timer_diff(&before, &after), num_req);

  fflush(NULL);
  result = final;
  return 0;
}
